name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Also run this workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version that matches your environment

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider  # Set the environment variable
        run: npm run build --if-present

      - name: Verify build success
        run: |
          if [ ! -d "build" ]; then
            echo "Build directory does not exist. Build failed."
            exit 1
          fi
          echo "Build succeeded."
